### ISSUE TITLE
error at first login

### ISSUE THREAD

**Issue by oljanssen** [openpim/documentation#2]
After successfull installation on Windows 10, I receive an error with the first login. 

I used the admin/admin login credentials. However looking into the database the password set for the admin user is $2b$10$WtKEm5gspljprGVuHAj4QeO.QwzWiDmdEFN9VzXRbxyrSpQi9m4Fq . Is it encrypted or is this the real password?
![error openpim login](https://github.com/openpim/documentation/assets/30273404/a72dafbb-0ada-435a-b7fa-661a1e2a594b)

what could be the issue causing this?

Also adding below the error messages in the browser console
 
![console error](https://github.com/openpim/documentation/assets/30273404/711cf12c-5611-490f-aba6-cbeaad747ae5)

**Comment by openpim** [comment]
Hi,

You should take a look at server log to see the problem. You can run 

docker container logs <pim_container_id> to see the logs.

But most of times the problem is that people specify "localhost" as DB address. Problem is that the system is running inside docker container so "localhost" is not the host server, but the container itself. So it is necessary to specify external DB address.

But when you will see the logs we will have more info

**Comment by oljanssen** [comment]
Hi,

 

Thanks for your reply. 

Yes, I specified localhost as the db name. Can I undo it or should I just rerun the installation with then the specific ip address as the db address?

Below is a screenshot of the logs.

 



 

Thanks for your support.

**Comment by openpim** [comment]
You are using a some command to start the docker with all necessary parameters. So you should change the parameter and start the system one more time. Also if you just want to take a look at the system, you can run the local demo

docker run -d -p 80:80 openpim/demo:2.0

in this case you will have database with demo data inside and you can play with the system

**Comment by oljanssen** [comment]
Ok. I did that and have the following log:

2024-03-13 11:08:48 (sequelize) Warning: PostgresSQL does not support 'INTEGER' with LENGTH, UNSIGNED or ZEROFILL. Plain 'INTEGER' will be used instead. 

2024-03-13 11:08:48 >> Check: http://www.postgresql.org/docs/9.4/static/datatype.html

2024-03-13 11:08:48 /server/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:142

2024-03-13 11:08:48                 reject(new sequelizeErrors.ConnectionError(err));

2024-03-13 11:08:48                        ^

2024-03-13 11:08:48 

2024-03-13 11:08:48 ConnectionError [SequelizeConnectionError]: no pg_hba.conf entry for host "192.168.178.53", user "postgres", database "pimJanssentrack", no encryption

2024-03-13 11:08:48     at Client._connectionCallback (/server/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:142:24)

2024-03-13 11:08:48     at Client._handleErrorWhileConnecting (/server/node_modules/pg/lib/client.js:305:19)

2024-03-13 11:08:48     at Client._handleErrorMessage (/server/node_modules/pg/lib/client.js:325:19)

2024-03-13 11:08:48     at Connection.emit (node:events:513:28)

2024-03-13 11:08:48     at /server/node_modules/pg/lib/connection.js:114:12

2024-03-13 11:08:48     at Parser.parse (/server/node_modules/pg-protocol/dist/parser.js:40:17)

2024-03-13 11:08:48     at Socket.<anonymous> (/server/node_modules/pg-protocol/dist/index.js:11:42)

2024-03-13 11:08:48     at Socket.emit (node:events:513:28)

2024-03-13 11:08:48     at addChunk (node:internal/streams/readable:315:12)

2024-03-13 11:08:48     at readableAddChunk (node:internal/streams/readable:289:9) {

2024-03-13 11:08:48   parent: error: no pg_hba.conf entry for host "192.168.178.53", user "postgres", database "pimJanssentrack", no encryption

2024-03-13 11:08:48       at Parser.parseErrorMessage (/server/node_modules/pg-protocol/dist/parser.js:287:98)

2024-03-13 11:08:48       at Parser.handlePacket (/server/node_modules/pg-protocol/dist/parser.js:126:29)

2024-03-13 11:08:48       at Parser.parse (/server/node_modules/pg-protocol/dist/parser.js:39:38)

2024-03-13 11:08:48       at Socket.<anonymous> (/server/node_modules/pg-protocol/dist/index.js:11:42)

2024-03-13 11:08:48       at Socket.emit (node:events:513:28)

2024-03-13 11:08:48       at addChunk (node:internal/streams/readable:315:12)

2024-03-13 11:08:48       at readableAddChunk (node:internal/streams/readable:289:9)

2024-03-13 11:08:48       at Socket.Readable.push (node:internal/streams/readable:228:10)

2024-03-13 11:08:48       at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {

2024-03-13 11:08:48     length: 169,

2024-03-13 11:08:48     severity: 'FATAL',

2024-03-13 11:08:48     code: '28000',

2024-03-13 11:08:48     detail: undefined,

2024-03-13 11:08:48     hint: undefined,

2024-03-13 11:08:48     position: undefined,

2024-03-13 11:08:48     internalPosition: undefined,

2024-03-13 11:08:48     internalQuery: undefined,

2024-03-13 11:08:48     where: undefined,

2024-03-13 11:08:48     schema: undefined,

2024-03-13 11:08:48     table: undefined,

2024-03-13 11:08:48     column: undefined,

2024-03-13 11:08:48     dataType: undefined,

2024-03-13 11:08:48     constraint: undefined,

2024-03-13 11:08:48     file: 'auth.c',

2024-03-13 11:08:48     line: '542',

2024-03-13 11:08:48     routine: 'ClientAuthentication'

2024-03-13 11:08:48   },

2024-03-13 11:08:48   original: error: no pg_hba.conf entry for host "192.168.178.53", user "postgres", database "pimJanssentrack", no encryption

2024-03-13 11:08:48       at Parser.parseErrorMessage (/server/node_modules/pg-protocol/dist/parser.js:287:98)

2024-03-13 11:08:48       at Parser.handlePacket (/server/node_modules/pg-protocol/dist/parser.js:126:29)

2024-03-13 11:08:48       at Parser.parse (/server/node_modules/pg-protocol/dist/parser.js:39:38)

2024-03-13 11:08:48       at Socket.<anonymous> (/server/node_modules/pg-protocol/dist/index.js:11:42)

2024-03-13 11:08:48       at Socket.emit (node:events:513:28)

2024-03-13 11:08:48       at addChunk (node:internal/streams/readable:315:12)

2024-03-13 11:08:48       at readableAddChunk (node:internal/streams/readable:289:9)

2024-03-13 11:08:48       at Socket.Readable.push (node:internal/streams/readable:228:10)

2024-03-13 11:08:48       at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {

2024-03-13 11:08:48     length: 169,

2024-03-13 11:08:48     severity: 'FATAL',

2024-03-13 11:08:48     code: '28000',

2024-03-13 11:08:48     detail: undefined,

2024-03-13 11:08:48     hint: undefined,

2024-03-13 11:08:48     position: undefined,

2024-03-13 11:08:48     internalPosition: undefined,

2024-03-13 11:08:48     internalQuery: undefined,

2024-03-13 11:08:48     where: undefined,

2024-03-13 11:08:48     schema: undefined,

2024-03-13 11:08:48     table: undefined,

2024-03-13 11:08:48     column: undefined,

2024-03-13 11:08:48     dataType: undefined,

2024-03-13 11:08:48     constraint: undefined,

2024-03-13 11:08:48     file: 'auth.c',

2024-03-13 11:08:48     line: '542',

2024-03-13 11:08:48     routine: 'ClientAuthentication'

2024-03-13 11:08:48   }

2024-03-13 11:08:48 }

**Comment by openpim** [comment]
ok, now you should add the configuration to the database to allow to connect from the IP (192.168.178.53) where the system is running.
Please take a look at official documentation about this - https://www.postgresql.org/docs/current/auth-pg-hba-conf.html
